I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tch1.rpy", line 80, in script
    t "Yeah! Look at how cute this girl is on my shirt!"
  File "game/tch1.rpy", line 80, in <module>
    t "Yeah! Look at how cute this girl is on my shirt!"
NameError: name 'weeb' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tch1.rpy", line 80, in script
    t "Yeah! Look at how cute this girl is on my shirt!"
  File "C:\Users\owner\Downloads\RenPy\renpy-7.1.1-sdk\renpy\ast.py", line 1760, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\owner\Downloads\RenPy\renpy-7.1.1-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\owner\Downloads\RenPy\renpy-7.1.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/tch1.rpy", line 80, in <module>
    t "Yeah! Look at how cute this girl is on my shirt!"
NameError: name 'weeb' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Galaxies 0.56.1b
Mon Oct 22 13:44:41 2018
